### PR TITLE
Add Go implementation

### PR DESCRIPTION
**Pull request by cristaloleg**

### CODE REVIEW

**Comment by galdor** [comment]
Seems we started roughly at the same moment! I published a [Go implementation](https://github.com/galdor/go-thumbhash) using the standard Go `image.Image` type, a command line tool and a few extra features (decoding options for larger images for example).

Hope it's ok to link to it, feel free to delete this comment if not.

**Comment by evanw** [comment]
Thanks for your PR! However, I have decided to link to third-party implementations instead of hosting them within this repo. Can you move this code into another repo and change this PR to link to your code from this repo's README?

@galdor I just linked your implementation in the README, so no PR is needed for your implementation.

**Comment by cristaloleg** [comment]
🤷

**Comment by galdor** [comment]
> Thanks for your PR! However, I have decided to link to third-party implementations instead of hosting them within this repo. Can you move this code into another repo and change this PR to link to your code from this repo's README?
> 
> @galdor I just linked your implementation in the README, so no PR is needed for your implementation.

Thank you. Listing all implementations on the README is indeed the simplest approach.

**Pull request closed without merging**
